In [1]:
import numpy as np
from PIL import Image

def image_to_matrix(image_path):
    image = Image.open(image_path).convert('L')
    matrix = np.array(image)
    return matrix

def crop_matrix(matrix, x_start, y_start, width, height):
    cropped_matrix = matrix[y_start:y_start+height, x_start:x_start+width]
    return cropped_matrix

def rotate_matrix(matrix, angle):
    angle = angle % 360
    rows, cols = matrix.shape  # Get the number of rows and columns in the matrix

    if angle == 0:
        return matrix

    if angle == 90:
        rotated_matrix = np.zeros((cols, rows), dtype=np.uint8)
        for i in range(rows):
            for j in range(cols):
                rotated_matrix[j, rows - i - 1] = matrix[i, j]
    elif angle == 180:
        rotated_matrix = np.zeros_like(matrix)
        for i in range(rows):
            for j in range(cols):
                rotated_matrix[rows - i - 1, cols - j - 1] = matrix[i, j]
    elif angle == 270:
        rotated_matrix = np.zeros((cols, rows), dtype=np.uint8)
        for i in range(rows):
            for j in range(cols):
                rotated_matrix[j, i] = matrix[i, j]
    else:
        rotated_matrix = matrix

    return rotated_matrix

def reverse_rows(matrix, horizontal=True):
    reversed_matrix = matrix.copy()
    if horizontal:
        rows, cols = matrix.shape
        for i in range(rows):
            left = 0
            right = cols - 1
            while left < right:
                reversed_matrix[i, left], reversed_matrix[i, right] = reversed_matrix[i, right], reversed_matrix[i, left]
                left += 1
                right -= 1
    else:
        rows, cols = matrix.shape
        top = 0
        bottom = rows - 1
        while top < bottom:
            for j in range(cols):
                reversed_matrix[top, j], reversed_matrix[bottom, j] = reversed_matrix[bottom, j], reversed_matrix[top, j]
            top += 1
            bottom -= 1
    return reversed_matrix

def matrix_to_image(matrix):
    image = Image.fromarray(matrix)
    return image

image_path = input("Enter the path of the image: ")
image_matrix = image_to_matrix(image_path)

print("\nOriginal Image Matrix:")
print(image_matrix)

original_image = matrix_to_image(image_matrix)
original_image.show(title='Original Image')

choice = input("Enter your choice (1 for cropping, 2 for rotation, 3 for flipping): ")

if choice == "1":
    x_start = int(input("Enter the x-coordinate of the top-left corner of the crop region: "))
    y_start = int(input("Enter the y-coordinate of the top-left corner of the crop region: "))
    width = int(input("Enter the width of the crop region: "))
    height = int(input("Enter the height of the crop region: "))

    cropped_matrix = crop_matrix(image_matrix, x_start, y_start, width, height)

    print("\nCropped Image Matrix:")
    print(cropped_matrix)

    cropped_image = matrix_to_image(cropped_matrix)
    cropped_image.save('cropped_image.jpg')
    cropped_image.show(title='Cropped Image')

elif choice == "2":
    angle = int(input("Enter the rotation angle (in degrees): "))

    rotated_matrix = rotate_matrix(image_matrix, angle)

    print("\nRotated Image Matrix:")
    print(rotated_matrix)

    rotated_image = matrix_to_image(rotated_matrix)
    rotated_image.show(title='Rotated Image')

    original_image.show(title='Original Image')

elif choice == "3":
    flip_type = input("Enter the flip type (1 for horizontal flip, 2 for vertical flip): ")

    if flip_type == "1":
        flipped_matrix = reverse_rows(image_matrix, horizontal=True)
        flip_text = "Horizontal"
    elif flip_type == "2":
        flipped_matrix = reverse_rows(image_matrix, horizontal=False)
        flip_text = "Vertical"
    else:
        print("Invalid flip type.")
        exit()

    print(f"\n{flip_text} Flipped Image Matrix:")
    print(flipped_matrix)

    flipped_image = matrix_to_image(flipped_matrix)
    flipped_image.show(title=f'{flip_text} Flip')

    original_image.show(title='Original Image')


Original Image Matrix:
[[ 2  2  2 ...  0  0  0]
 [ 1  0  1 ...  0  0  0]
 [ 7  7  7 ...  6  6  6]
 ...
 [48 48 48 ... 30 30 30]
 [48 48 48 ... 30 30 30]
 [48 48 48 ... 30 30 30]]

Cropped Image Matrix:
[[109 109 112 ... 115 113 111]
 [112 109 112 ... 113 111 108]
 [112 114 111 ... 110 107 105]
 ...
 [ 88  88  86 ... 191 189 188]
 [ 88  88  86 ... 190 189 188]
 [ 89  89  89 ... 190 188 185]]
